cache: bundler
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-9.2.11.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.11.0

script:
        - CODECLIMATE_REPO_TOKEN=44310fa9af74b45d5b6165d24ddeb268754f46f6de57e1bf5b4c3b997bb6c812 bundle exec rake test:spec

addons:
  code_climate:
    repo_token: 44310fa9af74b45d5b6165d24ddeb268754f46f6de57e1bf5b4c3b997bb6c812

notifications:
  email:
    recipients:
      - benny.klotz92@gmail.com
    email:
      on_failure: change
      on_success: change
