language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ruby-head
  - jruby
  - rbx-2.2.9
  - rbx-2.2.10

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - "COVERAGE=true bundle exec bin/test_runner"

notifications:
  email:
    recipients:
      - r3qnbenni@gmail.com
    email:
      on_failure: change
      on_success: change
