cache: bundler
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9000
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3

script:
  - CODECLIMATE_REPO_TOKEN=44310fa9af74b45d5b6165d24ddeb268754f46f6de57e1bf5b4c3b997bb6c812 bundle exec bin/spec_runner

addons:
  code_climate:
    repo_token: 44310fa9af74b45d5b6165d24ddeb268754f46f6de57e1bf5b4c3b997bb6c812

notifications:
  email:
    recipients:
      - benny.klotz92@gmail.com
    email:
      on_failure: change
      on_success: change
