cache: bundler
sudo: false

before_install:
  - gem update --system
  - gem --version
  - gem install bundler

rvm:
  - 2.1.5
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head

script:
  - "COVERAGE=true bundle exec bin/spec_runner"

notifications:
  email:
    recipients:
      - benny.klotz92@gmail.com
    email:
      on_failure: change
      on_success: change
